batch_size: 1
epochs: 10000
lr: 0.0001

device: "cuda"
workers: 4

vis_images: 200  # number of visualization images to save in log file (default: 200)
vis_freq: 10  # frequency of saving images to log file (default: 10)

weights: "./weights"  # folder to save weights
logs: "./logs"  # folder to save logs
#images_path: "/data3/adolf/ocr_hup/object_detection/data/gaoda/12_08"  # root folder with images
images_path: "/datadisk2/ocr_data/idcard_detection"

image_size: 1024  # target input image size (default: 256)

aug_scale: 0.05  # scale factor range for augmentation (default: 0.05)
aug_angle: 15  # rotation angle range in degrees for augmentation (default: 15)